pipeline {
    agent {
        docker {
            image 'dussim/build-env:jdk25_gradle-9.2.1_android-36'
            args '-v gradle-cache:/home/gradle/.gradle --net=host'
        }
    }
    stages {
        stage('Workflow') {
            steps {
                sh 'cat .jenkins/Jenkinsfile'
            }
        }
        stage('Gradle'){
            steps {
                sh './gradlew --version'
                sh './gradlew --status'
                sh './gradlew buildEnvironment'
                sh './gradlew -q javaToolchains'
            }
        }
        stage('Build') {
            steps {
                sh './gradlew :app:assembleDebug --scan'
                recordIssues([
                        enabledForFailure: true,
                        tool             : kotlin()
                ])
                findBuildScans()
            }
        }
        stage('Quality') {
            steps {
                sh './gradlew ktlintCheck'
                recordIssues([
                        enabledForFailure: true,
                        tool             : ktLint(pattern: '**/build/reports/ktlint/**/*.xml')
                ])
            }
        }
        stage('Versions') {
            steps {
                sh './gradlew dependencyUpdates --no-parallel -Dorg.gradle.unsafe.isolated-projects=false'
            }
        }
    }
    post {
        always {
            echo 'Archiving artifacts'
            archiveArtifacts([
                    allowEmptyArchive: true,
                    artifacts        : 'app/build/outputs/apk/**/*.apk'
            ])
            archiveArtifacts([
                    allowEmptyArchive: true,
                    artifacts        : '.reports/**/*.html'
            ])
            archiveArtifacts([
                    allowEmptyArchive: true,
                    artifacts        : 'build/reports/**/*.html'
            ])
            publishHTML([
                    allowMissing         : true,
                    alwaysLinkToLastBuild: false,
                    keepAll              : false,
                    reportDir            : '.reports',
                    reportFiles          : '**/*.html',
                    reportName           : 'Aggregated Reports',
            ])
            publishHTML([
                    allowMissing         : true,
                    alwaysLinkToLastBuild: false,
                    keepAll              : false,
                    reportDir            : 'build/reports/',
                    reportFiles          : '**/*.html',
                    reportName           : 'Build Reports',
            ])
        }
    }
}