pipeline {
    agent {
        docker {
            image 'dussim/build-env:jdk25_gradle-9.3.0_android-36'
            args '-v gradle-cache:/home/gradle/.gradle --net=host'
        }
    }
    stages {
        stage('Workflow') {
            steps {
                sh 'cat .jenkins/Jenkinsfile'
            }
        }
        stage('Gradle'){
            steps {
                sh 'gradle --version'
                sh 'gradle --status'
                sh 'gradle buildEnvironment'
                sh 'gradle -q javaToolchains'
            }
        }
        stage('Build') {
            steps {
                sh 'gradle :app:assembleDebug --scan'
                recordIssues([
                        enabledForFailure: true,
                        tool             : kotlin()
                ])
                findBuildScans()
            }
        }
        stage('Quality') {
            steps {
                sh 'gradle ktlintCheck'
                recordIssues([
                        enabledForFailure: true,
                        tool             : ktLint(pattern: '**/build/reports/ktlint/**/*.xml')
                ])
            }
        }
// disabled because android plugin does some stupid things (like always) that cause this plugin to throw exception
//         stage('Versions') {
//             steps {
//                 sh 'gradle dependencyUpdates --no-parallel -Dorg.gradle.unsafe.isolated-projects=false'
//             }
//         }
    }
    post {
        always {
            echo 'Archiving artifacts'
            archiveArtifacts([
                    allowEmptyArchive: true,
                    artifacts        : 'app/build/outputs/apk/**/*.apk'
            ])
            archiveArtifacts([
                    allowEmptyArchive: true,
                    artifacts        : '.reports/**/*.html'
            ])
            archiveArtifacts([
                    allowEmptyArchive: true,
                    artifacts        : 'build/reports/**/*.html'
            ])
            publishHTML([
                    allowMissing         : true,
                    alwaysLinkToLastBuild: false,
                    keepAll              : false,
                    reportDir            : '.reports',
                    reportFiles          : '**/*.html',
                    reportName           : 'Aggregated Reports',
            ])
            publishHTML([
                    allowMissing         : true,
                    alwaysLinkToLastBuild: false,
                    keepAll              : false,
                    reportDir            : 'build/reports/',
                    reportFiles          : '**/*.html',
                    reportName           : 'Build Reports',
            ])
        }
    }
}